# Generated by Django 4.1 on 2022-08-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
