# Generated by Django 4.1 on 2022-08-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsAmount',
            new_name='RecipesIngredient',
        ),
    ]
