# Generated by Django 4.1 on 2022-08-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_ingredientsamount_recipesingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredient',
            name='ingredient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ingredient_to_recipe',
                to='recipes.ingredient',
            ),
        ),
        migrations.AlterField(
            model_name='recipesingredient',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipe_to_ingredient',
                to='recipes.recipe',
            ),
        ),
    ]
