# Generated by Django 4.1 on 2022-08-28 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_alter_recipesingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favotites',
            new_name='Favotite',
        ),
    ]
