# Generated by Django 4.1 on 2022-08-28 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_rename_favotites_favotite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favotite',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fav_recipe_to_user',
                to='recipes.recipe',
            ),
        ),
        migrations.AlterField(
            model_name='favotite',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fav_user_to_recipe',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
