# Generated by Django 4.1 on 2022-08-29 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_alter_shoppingcart_recipe_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favotite',
            name='unique_favotites)',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping)',
        ),
        migrations.AlterField(
            model_name='favotite',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite',
                to='recipes.recipe',
            ),
        ),
        migrations.AlterField(
            model_name='favotite',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='shopping_cart',
                to='recipes.recipe',
            ),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name='favotite',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'), name='unique_fav_recipes)'
            ),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'), name='unique_cart_recipes)'
            ),
        ),
    ]
