# Generated by Django 4.1 on 2022-08-30 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0014_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favotite',
            new_name='Favorite',
        ),
    ]
