# Generated by Django 4.1 on 2022-09-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'recipes',
            '0020_alter_favorite_options_alter_recipe_options_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'ordering': ['-pub_date'],
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
