# Generated by Django 4.1 on 2022-09-02 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_subscription_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={
                'ordering': ('user', 'author'),
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ('username',),
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscribes',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор',
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscribers',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
